---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    logging: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
  labels:
    name: tracing
    tracing: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
  labels:
    name: gitops
    gitops: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    gitops: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    name: kube-system
