apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tracing
  namespace: tracing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tempo.kubewatch.local
      secretName: tracing-tls
  rules:
    - host: tempo.kubewatch.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tempo
                port:
                  number: 3200
